remove box2d build error caused by doctest
the following is the error

box2d_v2_4_1/unit-test/doctest.h:4021:47: error: size of array ‘altStackMem’ is not an integral constant-expression